const express = require("express")
const router = express.Router()

const {createRule, createSqlQuery, addToParameterList} = require('../controllers/createRule')
const {debugRule} = require('../controllers/debugRule')
const {modifyRule} = require('../controllers/modifyRule')
const {getAllRules, getAllparameter} = require('../controllers/viewAllRules')
const {ruleHasParameters, testRule, sampleRoute} = require('../controllers/testRule')
const {dbFileQuery} = require('../controllers/DbFileQuery')
const {databaseFileUpload} = require('../controllers/FileUpload')
const {chatbotCreateRule, fetchAllRulesForChatbot, chatbotCompletions} = require('../controllers/chatbotController')
const {protect} = require("../controllers/auth")

router.post('/createRule', protect, createRule)
router.post('/createChatbotRule', protect, chatbotCreateRule)
router.get('/chatbotRules', protect, fetchAllRulesForChatbot)
router.post('/debugRule', protect, debugRule)
router.post('/modifyRule', protect, modifyRule)
router.get('/ruleHasParameters/:id', protect, ruleHasParameters)
router.get('/getAllRules', protect, getAllRules)
router.post('/testRule/:id', protect, testRule)
router.post('/sampleRoute', sampleRoute)
router.post('/dbfilequery', dbFileQuery)
router.post('/uploaddbfile', databaseFileUpload)
router.post("/completions", chatbotCompletions)
router.post("/sqlquery", createSqlQuery)
router.post("/addparameters", addToParameterList)
router.get("/getallparams", getAllparameter)

module.exports = router